# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:h2testdb
    username: h2testuser
    password: h2pass
